name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3, 8.4, 8.5]
        laravel: [10, 11, 12, 13]
        stability: ["prefer-lowest", "prefer-stable"]
        exclude:
          - php: 8.5
            laravel: 10
          - php: 8.5
            laravel: 11
          - php: 8.4
            laravel: 10
          - php: 8.2
            laravel: 13
          - php: 8.1
            laravel: 11
          - php: 8.1
            laravel: 12
          - php: 8.1
            laravel: 13

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} (w/ ${{ matrix.stability }})
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Remove Larastan
        run: composer remove --dev larastan/larastan --no-update

      - name: Set Minimum PHP 8.1 Versions
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require vlucas/phpdotenv:^5.3.1 --${{ matrix.stability }} --no-update --no-interaction
        if: matrix.php >= 8.1 && matrix.stability == 'prefer-lowest'

      - name: Set Minimum PHP 8.2 Versions
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require nesbot/carbon:^2.62.1 --dev --${{ matrix.stability }} --no-update --no-interaction
        if: matrix.php >= 8.2 && matrix.stability == 'prefer-lowest' && matrix.laravel < 12

      - name: Set Minimum PHP 8.2 Versions and Laravel > 11
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require "orchestra/testbench:^9.2|^10.0|^11.0" --dev --${{ matrix.stability }} --no-update --no-interaction
        if: matrix.php >= 8.2 && matrix.stability == 'prefer-lowest' && matrix.laravel >= 11

      - name: Set Laravel version
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework=^${{ matrix.laravel }}" --no-interaction --no-update

      - name: Install dependencies
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
